apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogs-analyzer
  labels:
    app: blogs-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogs-analyzer
  template:
    metadata:
      labels:
        app: blogs-analyzer
    spec:
      containers:
        - name: blogs-analyzer
          image: gcr.io/gen-lang-client-0999974873/blogs-analyzer:latest
          ports:
            - containerPort: 8888
          imagePullPolicy: Always
