apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogs-analyzer
  labels:
    app: blogs-analyzer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blogs-analyzer
  template:
    metadata:
      labels:
        app: blogs-analyzer
    spec:
      containers:
        - name: blogs-analyzer
          image: gcr.io/gen-lang-client-0999974873/blogs-analyzer:latest
          env:
            - name: GOOGLE_GEMINI_API_KEY
              value: "AIzaSyBVXC1CEsJvqu3Lp9f_QuFoLYuzP3yJTGU"
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          imagePullPolicy: Always
