name: GCP CI/CD Pipeline

on:
  push:
    branches:
      - '**'

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  CLUSTER_NAME: blogs-analyzer-cluster
  REGION: ${{ secrets.GKE_ZONE }}
  REGISTRY_NAME: blogs-analyzer
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup for Java projects
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Build Java services
      - name: Build Java services
        run: |
          SERVICE_NAMES=$(cat projects-changes-deploy.txt)
          echo "Service Names: $SERVICE_NAMES"
          for SERVICE_NAME in $(echo $SERVICE_NAMES | tr ',' ' '); do
            echo "Building $SERVICE_NAME"

            # Set the build context to the root directory
            if [ -d "$SERVICE_NAME" ]; then
              cd $SERVICE_NAME
              if [ "$SERVICE_NAME" != "blogs-analyzer-ui" ]; then
                mvn clean install -B -V
              fi
              cd ..
            fi
          done

      # Setup for Angular projects
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      # Install dependencies for Angular projects
      - name: Install dependencies for Angular projects
        run: |
          SERVICE_NAMES=$(cat projects-changes-deploy.txt)
          echo "Service Names: $SERVICE_NAMES"
          for SERVICE_NAME in $(echo $SERVICE_NAMES | tr ',' ' '); do
            echo "Processing Service: $SERVICE_NAME"
            if [ -d "$SERVICE_NAME" ]; then
              cd $SERVICE_NAME
              if [ "$SERVICE_NAME" == "blogs-analyzer-ui" ]; then
                npm install
              fi
              cd ..
            fi
          done

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.GKE_PROJECT }}
          service_account_key: ${{ env.SERVICE_ACCOUNT_KEY }}

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.5.0
        with:
          credentials_json: ${{ env.SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker for Google Container Registry
        run: gcloud auth configure-docker

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Build and push Docker images
        run: |
          SERVICE_NAMES=$(cat projects-changes-deploy.txt)
          echo "Service Names: $SERVICE_NAMES"
          for SERVICE_NAME in $(echo $SERVICE_NAMES | tr ',' ' '); do
            echo "Building and pushing Docker image for $SERVICE_NAME"
            if [ -d "$SERVICE_NAME" ]; then
              cd $SERVICE_NAME
              IMAGE_NAME=gcr.io/gen-lang-client-0999974873/$SERVICE_NAME:latest
              docker build -t $IMAGE_NAME .
              docker push $IMAGE_NAME
              cd ..
            fi
          done

      - name: Deploy to GKE
        run: |
          echo "Getting credentials for cluster ${{ env.CLUSTER_NAME }} in zone ${{ env.REGION }}"
          gcloud container clusters get-credentials blogs-analyzer-cluster --region asia-south1 --project gen-lang-client-0999974873
          SERVICE_NAMES=$(cat projects-changes-deploy.txt)
          echo "Service Names: $SERVICE_NAMES"
          for SERVICE_NAME in $(echo $SERVICE_NAMES | tr ',' ' '); do
            echo "Deploying $SERVICE_NAME to GKE"
            if [ -d "$SERVICE_NAME" ]; then
              cd $SERVICE_NAME/k8s
              kubectl apply -f .
              cd ../..
            fi
          done

  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup for Java projects
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Setup for Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      # Sonar Analysis for Java projects
      - name: Sonar Analysis for Java projects
        run: |
          SERVICE_NAMES=$(cat projects-changes-deploy.txt)
          echo "Service Names: $SERVICE_NAMES"
          for SERVICE_NAME in $(echo $SERVICE_NAMES | tr ',' ' '); do
            echo "Processing Service: $SERVICE_NAME"
            if [ -d "$SERVICE_NAME" ]; then
              cd $SERVICE_NAME
              if [ "$SERVICE_NAME" != "blogs-analyzer-ui" ]; then
                mvn clean verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=nashtech -Dsonar.branch.name=master
              fi
              cd ..
            fi
          done

      # Sonar Analysis for Angular projects
      - name: Sonar Analysis for Angular projects
        run: |
          SERVICE_NAMES=$(cat projects-changes-deploy.txt)
          echo "Service Names: $SERVICE_NAMES"
          for SERVICE_NAME in $(echo $SERVICE_NAMES | tr ',' ' '); do
            echo "Processing Service: $SERVICE_NAME"
            if [ -d "$SERVICE_NAME" ]; then
              cd $SERVICE_NAME
              if [ "$SERVICE_NAME" == "blogs-analyzer-ui" ]; then
                npm install
                npm test
                npm install -g sonarqube-scanner
                npm run sonar
              fi
              cd ..
            fi
          done
