name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup for Java projects
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Build and deploy Java services
      - name: Build and deploy Java services
        run: |
          SERVICE_NAMES=$(cat projects-changes-deploy.txt)
          echo "Service Names: $SERVICE_NAMES"
          for SERVICE_NAME in $(echo $SERVICE_NAMES | tr ',' ' '); do
            echo "Building and deploying $SERVICE_NAME"

            # Set the build context to the root directory
            cd $SERVICE_NAME
            if [ "$SERVICE_NAME" != "blogs-analyzer-ui" ]; then
                mvn clean install -B -V
            fi
          done

      # Setup for Angular projects
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Install dependencies and run tests for Angular projects
      - name: Install dependencies and run tests for Angular projects
        run: |
          SERVICE_NAMES=$(cat projects-changes-deploy.txt)
          echo "Service Names: $SERVICE_NAMES"
          for SERVICE_NAME in $(echo $SERVICE_NAMES | tr ',' ' '); do
            echo "Processing Service: $SERVICE_NAME"
            cd $SERVICE_NAME
            if [ "$SERVICE_NAME" == "blogs-analyzer-ui" ]; then
              npm install
              npm test --code-coverage
            fi
          done
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Sonar Analysis for Java projects
      - name: Sonar Analysis for Java projects
        run: |
          SERVICE_NAMES=$(cat projects-changes-deploy.txt)
          echo "Service Names: $SERVICE_NAMES"
          for SERVICE_NAME in $(echo $SERVICE_NAMES | tr ',' ' '); do
            echo "Processing Service: $SERVICE_NAME"
            cd $SERVICE_NAME
            if [ "$SERVICE_NAME" != "blogs-analyzer-ui" ]; then
              mvn clean verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=nashtech -Dsonar.branch.name=master
            fi
          done
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Sonar Analysis for Angular projects
      - name: Sonar Analysis for Angular projects
        run: |
          SERVICE_NAMES=$(cat projects-changes-deploy.txt)
          echo "Service Names: $SERVICE_NAMES"
          for SERVICE_NAME in $(echo $SERVICE_NAMES | tr ',' ' '); do
            echo "Processing Service: $SERVICE_NAME"
            cd $SERVICE_NAME
            if [ "$SERVICE_NAME" == "blogs-analyzer-ui" ]; then
              npm run sonar
            fi
          done
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
